{
 "title": "Aztec prover",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(target_info,aztec_network_name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(target_info{aztec_network_name=\"$network\"},exported_instance)"
    }
   },
   { "name": "interval", "query": "4h, 12h, 24h" },
   {
    "name": "protocol_circuit",
    "label": "Protocol circuit",
    "query": {
     "query": "label_values(aztec_circuit_protocol_circuit_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node system resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg by(exported_job, exported_instance) (system_cpu_utilization{system_cpu_state=\"idle\", exported_instance=~\"$instance\"})",
     "legendFormat": "{{exported_job}}-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(exported_job, exported_instance) (system_memory_utilization{exported_instance=~\"$instance\", system_memory_state=\"used\"})",
     "legendFormat": "{{exported_job}}-{{exported_instance}}"
    }
   ]
  },
  { "title": "L2 network status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Last block number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aztec_archiver_block_height{exported_instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(aztec_archiver_block_size{exported_instance=~\"$instance\"}[$__interval])",
     "legendFormat": "Last block size"
    }
   ]
  },
  {
   "title": "Block synch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg (rate(aztec_archiver_sync_duration_milliseconds_sum{exported_instance=~\"$instance\"}[$interval]) / rate(aztec_archiver_sync_duration_milliseconds_count{exported_instance=~\"$instance\"}[$interval])) by (exported_job, exported_instance)",
     "legendFormat": "AVG - {{exported_job}}-{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Incoming transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(aztec_node_receive_tx_count{exported_instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{aztec_ok}}"
    }
   ]
  },
  {
   "title": "Mempool status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(aztec_status) (aztec_mempool_tx_count{exported_instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx receive time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg (rate(aztec_node_receive_tx_duration_milliseconds_sum{exported_instance=~\"$instance\"}[$__rate_interval]) / rate(aztec_node_receive_tx_duration_milliseconds_count{exported_instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Tx size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(aztec_mempool_tx_size_bytes_sum{exported_instance=~\"$instance\"}[$interval]) / rate(aztec_mempool_tx_size_bytes_count{exported_instance=~\"$instance\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sequencer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Sequencer state",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aztec_sequencer_current_state{exported_instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aztec_sequencer_current_block_number{exported_instance=~\"$instance\"}",
     "legendFormat": "Next block number"
    },
    {
     "expr": "aztec_sequencer_current_block_size{exported_instance=~\"$instance\"}",
     "legendFormat": "Next block size"
    }
   ]
  },
  {
   "title": "Next block started at",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(aztec_sequencer_current_block_number{exported_instance=~\"$instance\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed bytecode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(aztec_public_processor_deploy_bytecode_size_bytes_sum{exported_instance=~\"$instance\"}[$interval]) / rate(aztec_public_processor_deploy_bytecode_size_bytes_count{exported_instance=~\"$instance\"}[$interval]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "L1 transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(aztec_l1_publisher_tx_count{exported_instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{aztec_l1_tx_type}}"
    }
   ]
  },
  {
   "title": "Block building duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(aztec_sequencer_block_build_duration_milliseconds_bucket{exported_instance=~\"$instance\"}[$interval])))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Tx simulation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(aztec_public_processor_tx_duration_milliseconds_sum{exported_instance=~\"$instance\"}[$__rate_interval]) / rate(aztec_public_processor_tx_duration_milliseconds_count{exported_instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "AVG - tx"
    },
    {
     "expr": "avg by (aztec_tx_phase_name) (rate(aztec_public_processor_phase_duration_milliseconds_sum{exported_instance=~\"$instance\"}[$__rate_interval]) / rate(aztec_public_processor_phase_duration_milliseconds_count{exported_instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "AVG - {{aztec_tx_phase_name}}"
    },
    {
     "expr": "avg(rate(aztec_public_executor_simulation_duration_milliseconds_sum{exported_instance=~\"$instance\"}[$__rate_interval]) / rate(aztec_public_executor_simulation_duration_milliseconds_count{exported_instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "AVG - fn"
    }
   ]
  },
  { "title": "Prover", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Queue depth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aztec_proving_queue_size{exported_instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Job size",
   "type": "stat",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (aztec_proving_job_type) (rate(aztec_proving_queue_job_size_by_sum{exported_instance=~\"$instance\"}[$interval]) / rate(aztec_proving_queue_job_size_by_count{exported_instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{aztec_proving_job_type}}"
    }
   ]
  },
  {
   "title": "Tree updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(aztec_proving_orchestrator_base_rollup_inputs_duration_milliseconds_sum{exported_instance=~\"$instance\"}[$interval]) / rate(aztec_proving_orchestrator_base_rollup_inputs_duration_milliseconds_count{exported_instance=~\"$instance\"}[$interval])",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Circuits stats - $protocol_circuit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "repeat": "protocol_circuit"
  },
  {
   "title": "Stats - $protocol_circuit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aztec_circuit_proving_proof_size_bytes{exported_instance=~\"$instance\", aztec_circuit_protocol_circuit_name=\"$protocol_circuit\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "aztec_circuit_public_inputs_count{exported_instance=~\"$instance\", aztec_circuit_protocol_circuit_name=\"$protocol_circuit\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Witness generation - $protocol_circuit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(aztec_circuit_witness_generation_duration_milliseconds_sum{aztec_circuit_protocol_circuit_name=\"$protocol_circuit\", exported_instance=~\"$instance\"}[$interval])/rate(aztec_circuit_witness_generation_duration_milliseconds_count{aztec_circuit_protocol_circuit_name=\"$protocol_circuit\", exported_instance=~\"$instance\"}[$interval]))",
     "legendFormat": "AVG"
    }
   ]
  },
  {
   "title": "Proving - $protocol_circuit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(aztec_circuit_proving_duration_milliseconds_sum{aztec_circuit_protocol_circuit_name=\"$protocol_circuit\", exported_instance=~\"$instance\"}[$interval])/rate(aztec_circuit_proving_duration_milliseconds_count{aztec_circuit_protocol_circuit_name=\"$protocol_circuit\", exported_instance=~\"$instance\"}[$interval]))",
     "legendFormat": "AVG"
    }
   ]
  }
 ]
}