{
 "title": "Bento",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Running Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM jobs WHERE state = 'running';"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM tasks WHERE state = 'running';"
    }
   ]
  },
  {
   "title": "Pending GPU tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n    tasks cross join lateral jsonb_object_keys(tasks.task_def) task_type\nWHERE\n  (\n    state = 'pending' OR state = 'ready'\n  ) AND (\n      task_type = 'Join' OR task_type = 'Prove' OR task_type = 'Resolve'\n  )"
    }
   ]
  },
  {
   "title": "Executor Tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(running) as running, SUM(ready) as ready FROM streams WHERE worker_type = 'exec'"
    }
   ]
  },
  {
   "title": "GPU Tasks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(running) as running, SUM(ready) as ready FROM streams WHERE worker_type = 'gpu'"
    }
   ]
  },
  {
   "title": "Job sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT job_id, min(started_at) as time, count(*) as tasks FROM tasks GROUP BY job_id ORDER BY time LIMIT 50"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  job_id,\n  res2.start_time,\n  res1.total_cycles,\n  res2.elapsed_sec,\n  CAST(res1.total_cycles AS decimal)  / res2.elapsed_sec AS hz\nFROM\n(\n  SELECT\n    job_id,\n    output->'total_cycles' total_cycles\n  FROM tasks\n  WHERE task_id = 'init'\n) res1\nJOIN\n(\n  SELECT \n    job_id as id2,\n    MIN(started_at) as start_time,\n    EXTRACT(EPOCH FROM (MAX(updated_at) - MIN(started_at))) AS elapsed_sec\n  FROM tasks GROUP BY job_id\n) res2\nON res1.job_id = res2.id2\n"
    }
   ]
  }
 ]
}